---
apiVersion: v1
kind: Namespace
metadata:
  name: 2804-oauth2-proxy
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: oauth2-proxy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: oauth2-proxy
  sourceRepos:
    - '*'
  destinations:
    - namespace: 2804-oauth2-proxy
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
