---
## Default values for Datadog Agent
## See Datadog helm documentation to learn more:
## https://docs.datadoghq.com/agent/kubernetes/helm/

datadog:
  apiKeyExistingSecret: datadog-secrets
  appKeyExistingSecret: datadog-secrets
  clusterName: stg-sbg-rancher-1065
  site: datadoghq.eu
  podLabelsAsTags:
    app: application
  tags:
    - "organization:wallet-services"
    - "env:stg"
    - "datacenter:sbg"
  nodeLabelsAsTags:
    service-id: service-id
    salt-env: salt-env
  # datadog.kubelet.tlsVerify should be `false` to establish communication with the kubelet
  kubelet:
    tlsVerify: "false"
  logs:
    enabled: true
    containerCollectAll: true
    containerCollectUsingFiles: true
  otlp:
    receiver:
      protocols:
        grpc:
          enabled: true
          useHostPort: false
  env:
    - name: DD_CONTAINER_EXCLUDE_LOGS
      value: "image:.*"
    - name: DD_CONTAINER_INCLUDE_LOGS
      value: "image:haproxytech/kubernetes-ingress name:^a4.* name:.*-indexer$ name:.*-api$ name:.*-pending$"
    - name: DD_CONTAINER_INCLUDE_METRICS
      value: "kube_namespace:1048-atlas" # if different per atlas env, shoud be moved to argocd appset
    - name: DD_DISABLE_CLUSTER_NAME_TAG_KEY
      value: "true"
    - name: DD_OTLP_CONFIG_METRICS_RESOURCE_ATTRIBUTES_AS_TAGS
      value: "true"
  processAgent:
    enabled: true
    processCollection: false
  systemProbe:
    enableTCPQueueLength: false
    enableOOMKill: true
    collectDNSStats: true
  networkMonitoring:
    enabled: true
  confd:
    disk.yaml: |
      init_config: {}
      instances:
        - use_mount: false
          device_exclude:
            - overlay
            - shm
            - tmpfs
            - udev
agents:
  ## https://docs.datadoghq.com/fr/containers/kubernetes/distributions/?tab=helm#Rancher
  tolerations:
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
      operator: Exists
  ## Fix for mountpoints that not detects by Datadog
  volumes:
    - hostPath:
        path: /boot
      name: boot
    - hostPath:
        path: /data
      name: data
  volumeMounts:
    - name: boot
      mountPath: /host/boot
      readOnly: true
    - name: data
      mountPath: /host/data
      readOnly: true
      mountPropagation: HostToContainer
