---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: 2802-oauth2-proxy-stg
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ledgerstg
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
