image:
  pullPolicy: IfNotPresent

config:
  logLevel: "trace"
  registries:
    - name: Github Container Registry
      prefix: ghcr.io
      api_url: https://ghcr.io
      ping: no
      credentials: pullsecret:argocd/ghcr-ledgerhq
      default: true
