apiVersion: v1
kind: Secret
data:
    .dockerconfigjson: ENC[AES256_GCM,data:HPTUdsxAYBBmDE8iENpxHsdrUQ4oqqFpy/aCf1uJJxqi2RzdMktbp7QlQHJmKRqo9740TEJUqWOqYNmh39KInri6BOoauSIkMTPRVXZiFCzyGxww9HZLdFJHYRGksGQkMf+IHhT1AaAhwIky16LDXX4O/ZMDelT/GgObzkt3k8q3Oo4uvz/0GyjDLn4BgLpdTbG+XfX5jTOzgUzNin8qNn1ZfbueGIePWqUmER36EfrEZMhgfV82YOfHlhCGnQ15lZv7XgIpCvYbP3NI5WvJ2Yo+dfHM2yxy/F6YSNvzxScDP0P0gF26OK03sYqvPxkPV6to7VbaFttoWpc8R45e/x627Os57AxSyYVl3cwlV4MT5tU/aXl4kKuCie9A+6CP,iv:6NCsjXvvQWzN5jdrBJF4cPnN/a0D0aI2W5GJVJQcnxc=,tag:nbjYnUnL5MGsUo+t9hAFOw==,type:str]
metadata:
    name: ghcr-ledgerhq
    namespace: argocd
type: kubernetes.io/dockerconfigjson
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cy0dfzdgkflyekgt8pf54wemhudm3wj5gzmc2jcc2jr2nkcuggwq2defr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMjdKcG13ZDF1akZyUUV1
            L2h5YXFiOXdzalVjZk1UMzFVOHlxRS9nMFFRCjBrMTNoS2k5TE5DT1czdGR4QWVE
            RmRIa0xNM3BZNUoxaXN6aUdiZ3prekUKLS0tIHl3bUNrUjEzS0hHRGVUUUdzWUhQ
            ME9NakUzM3p0OUNBdVBhUm5Vbzc5cUUKe9ts9E2QqLXVLc+WSwdBI48RAJtTxPUz
            X5s/KTpWUdWwJEf99HbXhrnm0cnmDEsDlqL7meQzP3GQtw7HZ2Yx4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-16T20:41:15Z"
    mac: ENC[AES256_GCM,data:exdknO09wLIduRk8+Ni0kZpt2zZapXjXjio1FL0SQaOF+Kr4gvtKM9Xs28yJnbjo0b2aMPD0O711o2mx+uykwKuIK/zoEc8IRIkQRCLl6iQenlzj4Gwa3tnip7MuhgYB+9XQh2FrEy2Gagq3AZKyCJ5OsSkJpqyo8Mfwxe2Jkz8=,iv:z2GzrmkhZvp1GX7KkytfmZ+GSqTWRWhzClXPUND4LLM=,tag:vDLZUGZ6lKSBBk3lAEDI0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
