---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  labels:
    environment: "sbx"
    owner: "team-infra-sre"
    project: "internal"
    organization: "infrastructure"
    service: "internal"
spec:
  project: internal
  source:
    repoURL: https://github.com/LedgerHQ/sre-argocd.git
    targetRevision: main
    path: deploy/sandbox-2042-cluster/applications
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated: {}
