---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: 2094/2803-oauth2-proxy-ppr
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ledgerprd
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
