---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps-of-apps
  namespace: argocd-central
  labels:
    owner: "team-infra-sre"
    project: "internal"
    organization: "infrastructure"
    service: "internal"
spec:
  project: internal
  source:
    repoURL: https://github.com/LedgerHQ/sre-argocd.git
    targetRevision: main
    path: deploy/platform-2220-cluster/argocd/prod
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd-central
  syncPolicy:
    automated: {}
