---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: redis-insight
  namespace: argocd-central
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: redis-insight
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
