---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: &app 2155-bento-stg
  namespace: argocd-central
  labels:
    environment: stg
    owner: data-team
    service-id: '2155'
    service: 'bento'
spec:
  project: *app
  sources:
    - chart: bento
      repoURL: https://warpstreamlabs.github.io/bento-helm-chart
      targetRevision: 0.1.0
      helm:
        releaseName: bento
        valueFiles:
          - "$values/deploy/platform-2220-cluster/applications/wallet-xp/non-prod-2020/2155-ledger-data-team/values.yaml"
    - repoURL: https://github.com/LedgerHQ/sre-argocd.git
      targetRevision: main
      path: "deploy/platform-2220-cluster/applications/wallet-xp/non-prod-2020/2155-ledger-data-team/manifests/"
    - repoURL: https://github.com/LedgerHQ/sre-argocd.git
      targetRevision: main
      ref: values
  destination:
    name: shared-application-2021-cluster
    namespace: 2155-ledger-data-team
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
