---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ms-oncall-notifier
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: ms-oncall-notifier tool
  sourceRepos:
    - 'https://github.com/LedgerHQ/infra-k8s-manifests.git'
  destinations:
    - namespace: tools
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
