apiVersion: v1
kind: Secret
metadata:
    name: argocd-helm-values
    labels:
        app.kubernetes.io/part-of: argocd
stringData:
    dex.googlegroups.clientID: ENC[AES256_GCM,data:PHKipchQW+wdnBUqtAu/VUXIsrJwAzKFCm21AzZve/sGHfuhPqltHnLBfs7aT5I6qm8BMT0h6CfgC/0aRdFf72ZpHyw+2JBT,iv:AG/CqYIOopk7jEqZcb2KhojIXPwRKcBUKKgVKJKqTXU=,tag:lNxxJl4OAZD8Jyoj03LoEA==,type:str]
    dex.googlegroups.clientSecret: ENC[AES256_GCM,data:JcCaSNDaVkoNAelnrmZ4tiWw3IcAFEHSA/ht6h2DfjV3abw=,iv:EZmyiYigiv2pooaG6aq66Cpxd5yruPhsMzAFEj4/25w=,tag:nqD2cV0nWGmj1bwhF2RWVw==,type:str]
    webhook.github.secret: ENC[AES256_GCM,data:vOcyynkRZkRsugIZwJ4tBlqBVnN9DhTbnExgA1o1,iv:xdhNfYaq/VC/Mmnc4d9DlEXg45rvp2SK8N34HmG4K/I=,tag:cBhWvkMzygk+Rff07Ac6NA==,type:str]
    random: ENC[AES256_GCM,data:E3ScRT33gnMwL3Jo/dDX7bkMp5beKZXrq1POvcYeTIpsvK9izB8PYKcMaIR5z03v,iv:DRzIZwQf8JO3yNOkf5miGainhAH5Z7GgnWJ2BVZIhks=,tag:KJOT8WnSTw0bgsJJonO0mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cy0dfzdgkflyekgt8pf54wemhudm3wj5gzmc2jcc2jr2nkcuggwq2defr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU0syL0k5WXNmd1ZCOVRC
            QzVKOGZBc0JmTkdUcUxIWmJKWmc2Q0NvREZNCm9PbG9YRk9DZWZQWWRBeFFMWUNN
            N2pXNkQ1c21pWnJIcGxhVzFqdWF0MDAKLS0tIHU4WUw2WmEyeEJTbjBhRmhTRlNP
            Nlo5NGNEUTE0c3RjdUJHTTRwbE4xUDgKqzNGPEnJkGauKBJY52rB1E1DlvVXYCW5
            Bt/8cj7P1FLBUj2J8E68YID5qlf2oGO+0jb9S1AUIpW/Sn2AkXINUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-14T09:38:03Z"
    mac: ENC[AES256_GCM,data:MAmGQyPqWBtwKzad6QpVNMtFLPi2BpO12QeOM51Y3OOGywMjEoH0BkCAR/yrTgAHSjG2Dc5+fqglT+oynDeqjD1QwPmGQmkWrilfL1X0pUSePhZGnwkcYpqW2Sqptjw5QZej7J7w+A14l/73qM1exewB2TDnFFph1WFIXDArXnE=,iv:u+HleU9VTMXD75tH113yg+ldteNUk7jHZRJF1UsI4Ec=,tag:p/mDKQhaWoyJF1EZ5eWsDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
