---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: backend-core-service-secrets-stg
  namespace: argocd-central
spec:
  generators:
    - list:
        elements:
          - app: countervalue-service
            project_id: '2034'
          - app: nano-appstore
            project_id: '2039'
          - app: web3checks-backend
            project_id: '2127'
          - app: crypto-assets-service
            project_id: '2211'
  template:
    metadata:
      name: '{{app}}-secret-stg'
      namespace: argocd-central
      labels:
        environment: stg
        owner: team-infra-sre
        project: '{{project_id}}'
        organization: 'wallet-services'
        service: '{{app}}'
    spec:
      project: backend-core-services
      source:
        repoURL: 'https://github.com/LedgerHQ/sre-argocd.git'
        targetRevision: main
        path: deploy/platform-2220-cluster/applications/wallet-xp/non-prod-2020/backend-core-services/secrets
      destination:
        name: shared-application-2021-cluster
        namespace: '{{project_id}}-{{app}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
  syncPolicy:
    preserveResourcesOnDeletion: true
