---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: lama-adapter-prd
  namespace: argocd-central
  labels:
    environment: "prd"
    owner: "team-infra-sre"
    project: "2302"
    organization: "wallet-services"
    service: "lama-adapter"
    service_family: "lama"
    service_group: "lama-adapter"
spec:
  project: lama-adapter-prd
  source:
    repoURL: https://github.com/LedgerHQ/lama-adapter.git
    targetRevision: main
    path: argocd/prd
    helm:
      releaseName: lama-adapter
      valueFiles:
        - 'values.yaml'
  destination:
    name: shared-application-2026-cluster
    namespace: 2302-lama-adapter-prd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
