---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: 1047-atlas
  namespace: argocd-central
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: 1047-atlas
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
