---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./datadog/bhs/app.yaml
  - ./datadog/fsn/app.yaml
  - ./datadog/rbx/app.yaml
  - ./ledger-explorer-exporter/app.yaml
  - ./namespace.yaml
