---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: 2801-oauth2-proxy-sbx
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ledgersbx
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
