---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: 2156-bento-prod
  namespace: argocd-central
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Bento data streaming service
  sourceRepos:
    - "*"
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
