---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  labels:
    service: "argo-workflows"
    env: "prd"
spec:
  project: internal
  source:
    repoURL: https://github.com/LedgerHQ/sre-argocd.git
    targetRevision: main
    path: deploy/shared-application-2086-cluster/applications/argo/argo-workflows
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
