---
appset:
  categoryValues:
    upstream:
      disableDefaultTagRevision: true
      path: ""

    gates-base:
      repoUrl: https://github.com/LedgerHQ/ledger-vault-api
      path: argocd/base
      inlineValues:
        image:
          repository: ghcr.io/ledgerhq/ledger-vault-api
        env:
          VAULT_ENABLE_APPLICATION_GROUP: true
          USE_GUNICORN: true
          VAULT_GUNICORN_WORKERS: 4 # we need to commit on a convention
          # if 1 request on the worker timeout, the worker (and all requests) is killed
          # so let workers enough time to handle long requests
          GUNICORN_TIMEOUT: 600
          VAULT_DB_MAX_CONNECTIONS: 5

    gates-520:
      targetRevision: 8.2.13
      inlineValues:
        custom:
          calVersion: 2024.31.2562
        env:
          VAULT_HSM_SCRIPTS_VERSION: 15.0.3

    gates-self16:
      targetRevision: 8.2.13
      inlineValues:
        custom:
          calVersion: 2024.32.2571
        env:
          VAULT_HSM_SCRIPTS_VERSION: 16.0.2

    hsmdrivers:
      repoUrl: https://github.com/LedgerHQ/ledger-vault-hsm-driver
      path: argocd/base
      targetRevision: 9.1.2
      inlineValues:
        image:
          repository: ghcr.io/ledgerhq/ledger-vault-hsm-driver

    hsmgateways:
      inlineValues:
        image:
          repository: ghcr.io/ledgerhq/hsm-gateway
      repoUrl: https://github.com/LedgerHQ/hsm-gateway-rs
      path: argocd/base
      targetRevision: 3.2.1
      useAppTemplate: true

    wds:
      repoUrl: https://github.com/LedgerHQ/ledger-wallet-daemon
      path: argocd/base
      targetRevision: 75395d6b000dd8fbc0fd95067ff12929d654350b
      useAppTemplate: true
      inlineValues:
        image:
          tag: 2.18.3
          repository: ghcr.io/ledgerhq/ledger-wallet-daemon

  projectValues:
    upstream:
      common-secrets:
        repoUrl: ghcr.io/ledgerhq/charts
        chartName: app-template
        targetRevision: 4.10.4
        inlineValues:
          controller:
            enabled: false
          service:
            main:
              enabled: false
      vault-rabbitmq:
        repoUrl: https://charts.bitnami.com/bitnami
        chartName: rabbitmq
        targetRevision: 12.15.0
        valueFiles:
          - $git-ledgerhq-sreargocd/deploy/platform-2220-cluster/applications/vault/common/values-rabbitmq.yaml
      keycloak:
        repoUrl: registry-1.docker.io/bitnamicharts
        chartName: keycloak
        targetRevision: 22.2.6
        valueFiles:
          - $git-ledgerhq-sreargocd/deploy/platform-2220-cluster/applications/vault/common/values-keycloak.yaml
        inlineValues:
          image:
            tag: 25.0.6-debian-12-r0
          production: true
          ingress:
            enabled: true
            hostnameStrict: true
            tls: true
          tls:
            enabled: true
            autoGenerated: true
          extraEnvVars: []
    all:
      api-gateway:
        repoUrl: https://github.com/LedgerHQ/vault-api-gateway
        useAppTemplate: true
        targetRevision: 1.29.2
        inlineValues:
          image:
            repository: ghcr.io/ledgerhq/vault-api-gateway

      api-keys:
        repoUrl: https://github.com/LedgerHQ/vault-api-keys
        useAppTemplate: true
        targetRevision: f9ee6150ae2b33b4f270afdb8689b583c837d242
        inlineValues:
          image:
            tag: 1.0.5
            repository: ghcr.io/ledgerhq/vault-api-keys

      apdu-connector:
        repoUrl: https://github.com/LedgerHQ/vault-apdu-connector
        useAppTemplate: true
        targetRevision: c70f608bfba5773a9edc51c82faafecdb2746baf
        inlineValues:
          image:
            tag: 1.1.0
            repository: ghcr.io/ledgerhq/vault-apdu-connector

      aum-api:
        repoUrl: https://github.com/LedgerHQ/vault-aum-api
        useAppTemplate: true
        targetRevision: ad486e1490aed44a46a04188d70e937b4cc86ffc
        inlineValues:
          image:
            tag: 5.9.2
            repository: ghcr.io/ledgerhq/vault-aum-api

      authentication-service:
        repoUrl: https://github.com/LedgerHQ/vault-authentication-service
        useAppTemplate: true
        targetRevision: 97fc7658dff10deac24ad62002f58260a4a8760c
        inlineValues:
          image:
            repository: ghcr.io/ledgerhq/vault-authentication-service
            tag: 1.0.4

      coin-gateway:
        repoUrl: https://github.com/LedgerHQ/coin-gateway
        useAppTemplate: true
        targetRevision: 1.30.0
        inlineValues:
          image:
            repository: ghcr.io/ledgerhq/coin-gateway

      dapp-manifest-api:
        repoUrl: https://github.com/LedgerHQ/dapp-manifest-api
        useAppTemplate: true
        targetRevision: 5d4a57127b2571551056b6ed54a31fd0bd44efb2
        inlineValues:
          image:
            tag: 0.4.4
            repository: ghcr.io/ledgerhq/dapp-manifest-api

      device-registry:
        repoUrl: https://github.com/LedgerHQ/vault-device-registry
        useAppTemplate: true
        targetRevision: 2.2.3
        inlineValues:
          image:
            repository: ghcr.io/ledgerhq/vault-device-registry

      front:
        repoUrl: https://github.com/LedgerHQ/ledger-vault-front
        targetRevision: 8.2.24
        inlineValues:
          image:
            repository: ghcr.io/ledgerhq/ledger-vault-front

      nfts-api:
        repoUrl: https://github.com/LedgerHQ/vault-nfts-api
        useAppTemplate: true
        targetRevision: 1.4.5
        inlineValues:
          image:
            repository: ghcr.io/ledgerhq/vault-nfts-api

      notification-center:
        repoUrl: https://github.com/LedgerHQ/vault-notification-center
        useAppTemplate: true
        targetRevision: c9500d7f689faf258069c832dd9964e0a8c9262c
        inlineValues:
          image:
            repository: ghcr.io/ledgerhq/vault-notification-center
            tag: 1.1.7

      notification-server:
        repoUrl: https://github.com/LedgerHQ/notification-server
        useAppTemplate: true
        targetRevision: 406cd87c4ae06f94f9da5ca9ca3d277d86562730
        inlineValues:
          image:
            repository: ghcr.io/ledgerhq/notification-server
            tag: 2.2.13

      notifier:
        repoUrl: https://github.com/LedgerHQ/vault-notifier
        targetRevision: 1.5.10
        inlineValues:
          image:
            repository: ghcr.io/ledgerhq/vault-notifier

      organizations-api:
        repoUrl: https://github.com/LedgerHQ/vault-organizations-api
        useAppTemplate: true
        targetRevision: 4.2.3
        inlineValues:
          image:
            repository: ghcr.io/ledgerhq/vault-organizations-api

      platform-manager:
        repoUrl: https://github.com/LedgerHQ/vault-platform-manager
        targetRevision: 4e5734b726981309baf2b806219e39246d2adb07
        inlineValues:
          image:
            repository: ghcr.io/ledgerhq/vault-platform-manager
            tag: 2.1.1

      revault-api:
        repoUrl: https://github.com/LedgerHQ/revault
        path: argocd/api
        targetRevision: api@1.4.0
        inlineValues:
          image:
            repository: ghcr.io/ledgerhq/revault-api
            tag: 1.4.0

      revault-onboarding:
        repoUrl: https://github.com/LedgerHQ/revault
        useAppTemplate: true
        targetRevision: onboarding@1.2.0
        path: argocd/onboarding
        inlineValues:
          image:
            repository: ghcr.io/ledgerhq/revault-onboarding
            tag: 1.2.0

      tx-scheduler:
        repoUrl: https://github.com/LedgerHQ/vault-tx-scheduler
        useAppTemplate: true
        targetRevision: 1.3.0
        inlineValues:
          image:
            repository: ghcr.io/ledgerhq/vault-tx-scheduler

      web3checks-vault:
        repoUrl: https://github.com/LedgerHQ/web3checks-vault
        useAppTemplate: true
        targetRevision: 1.1.1
        inlineValues:
          image:
            repository: ghcr.io/ledgerhq/web3checks-vault

      web3-handler-api:
        repoUrl: https://github.com/LedgerHQ/web3-handler-api
        useAppTemplate: true
        targetRevision: 1.4.3
        inlineValues:
          image:
            repository: ghcr.io/ledgerhq/web3-handler-api
