---
# yaml-language-server: $schema=../releases/release-vault-schema.json
appset:
  categoryValues:
    upstream:
      disableDefaultTagRevision: true
      path: ""

    gates-base:
      repoUrl: https://github.com/LedgerHQ/ledger-vault-api
      path: argocd/base

    gates-previous:
      targetRevision: 8.9.15

    gates-current:
      targetRevision: 8.11.14

    wds:
      repoUrl: https://github.com/LedgerHQ/ledger-wallet-daemon
      path: argocd/base
      targetRevision: 75395d6b000dd8fbc0fd95067ff12929d654350b
      useAppTemplate: true
      inlineValues:
        image:
          tag: 2.18.3

  projectValues:
    upstream:
      common-secrets:
        repoUrl: ghcr.io/ledgerhq/charts
        chartName: app-template
        targetRevision: 4.10.4
        inlineValues:
          controller:
            enabled: false
          service:
            main:
              enabled: false
      vault-rabbitmq:
        repoUrl: https://charts.bitnami.com/bitnami
        chartName: rabbitmq
        targetRevision: 12.15.0
        valueFiles:
          - $git-ledgerhq-sreargocd/deploy/platform-2220-cluster/applications/vault/common/values-rabbitmq.yaml
      keycloak:
        repoUrl: registry-1.docker.io/bitnamicharts
        chartName: keycloak
        targetRevision: 24.6.3
        valueFiles:
          - $git-ledgerhq-sreargocd/deploy/platform-2220-cluster/applications/vault/common/values-keycloak.yaml
        inlineValues:
          global:
            security:
              allowInsecureImages: true
          production: true
          ingress: # take care to move hostname from adminIngress to ingress block for 5.9.0
            enabled: true
            hostnameStrict: true
            tls: true
            ingressClassName: trusted
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
          adminIngress:
            enabled: false
          tls:
            enabled: true
            autoGenerated: true
          extraEnvVars: []
    all:
      api-keys:
        repoUrl: https://github.com/LedgerHQ/vault-api-keys
        useAppTemplate: true
        targetRevision: 1.0.6

      apdu-connector:
        repoUrl: https://github.com/LedgerHQ/vault-apdu-connector
        useAppTemplate: true
        targetRevision: c70f608bfba5773a9edc51c82faafecdb2746baf
        inlineValues:
          image:
            tag: 1.1.3

      aum-api:
        repoUrl: https://github.com/LedgerHQ/vault-aum-api
        useAppTemplate: true
        targetRevision: ad486e1490aed44a46a04188d70e937b4cc86ffc
        inlineValues:
          image:
            repository: ghcr.io/ledgerhq/vault-aum-api
            tag: 5.9.3

      authentication-service:
        repoUrl: https://github.com/LedgerHQ/vault-authentication-service
        useAppTemplate: true
        targetRevision: 1.1.1

      coin-gateway:
        repoUrl: https://github.com/LedgerHQ/coin-gateway
        useAppTemplate: true
        targetRevision: 1.34.0

      device-registry:
        repoUrl: https://github.com/LedgerHQ/vault-device-registry
        useAppTemplate: true
        targetRevision: 2.2.5

      front:
        repoUrl: https://github.com/LedgerHQ/ledger-vault-front
        targetRevision: 8.11.2

      nfts-api:
        repoUrl: https://github.com/LedgerHQ/vault-nfts-api
        useAppTemplate: true
        targetRevision: 1.4.7

      notification-center:
        repoUrl: https://github.com/LedgerHQ/vault-notification-center
        useAppTemplate: true
        targetRevision: 1.2.0

      notifier:
        repoUrl: https://github.com/LedgerHQ/vault-notifier
        targetRevision: 1.5.12

      organizations-api:
        repoUrl: https://github.com/LedgerHQ/vault-organizations-api
        useAppTemplate: true
        targetRevision: 4.2.4

      platform-manager:
        repoUrl: https://github.com/LedgerHQ/vault-platform-manager
        targetRevision: 4e5734b726981309baf2b806219e39246d2adb07
        inlineValues:
          image:
            tag: 2.4.0

      tradelink:
        repoUrl: https://github.com/LedgerHQ/vault-tradelink
        targetRevision: faa1b2f535ef90b061f1399b28c79105889d74ad
        useAppTemplate: true
        inlineValues:
          image:
            tag: 1.2.2

      tx-scheduler:
        repoUrl: https://github.com/LedgerHQ/vault-tx-scheduler
        useAppTemplate: true
        targetRevision: 1.3.4

      web3checks-vault:
        repoUrl: https://github.com/LedgerHQ/web3checks-vault
        useAppTemplate: true
        targetRevision: 1.1.2

      web3-handler-api:
        repoUrl: https://github.com/LedgerHQ/web3-handler-api
        useAppTemplate: true
        targetRevision: 1.5.0
