---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 2145-backend-services-keycloak-stg

helmCharts:
  - name: keycloak
    releaseName: keycloak
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 24.7.4
    valuesFile: values.yaml
