apiVersion: v1
kind: Secret
metadata:
    name: argocd-helm-values
    labels:
        app.kubernetes.io/part-of: argocd
stringData:
    dex.googlegroups.clientID: ENC[AES256_GCM,data:TIBGvCFh8ZFkXa24+guv3Djr62P0P7igklegC6gafFQXax75/kNpEwiQnbvWbwVpV5vO4FvBhDfRYLBhS1gBCFOdt0BIqJct,iv:adZXKgASPkCE24WgzvVlzundNlAHJJ4CrpYeXrxKScs=,tag:rLDmyNQteVvCUs0/J6ra5w==,type:str]
    dex.googlegroups.clientSecret: ENC[AES256_GCM,data:TA8+hfGvbe7OqQO75F/6C5bQwBPE/vHm7JGEi82goupw25U=,iv:3F8jTJkF1WcuZyymG4GQIjIbrCO9GvZ2JSBWEaafIK4=,tag:dXgBXz8PWtAqGkZgFyFRpg==,type:str]
    webhook.github.secret: ENC[AES256_GCM,data:Xy51/t+UAXVgbEkksh702/QMB6nsx30s6TBiHpvW,iv:LyNOiz7iaBAJxvtaBYcnx9pKfgYzMhVpAdgsITXdxT8=,tag:F6AzQdCKbV5vTmfInvKpZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cy0dfzdgkflyekgt8pf54wemhudm3wj5gzmc2jcc2jr2nkcuggwq2defr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodmpKSmdQSTJ5bmYwelZu
            cTMzbXRJMjhKZjc5aFVscnErNmxxcGd1czE0CjR0cXg1U2JBTGVHb3B1RDRrR3My
            ZmNFSjhQa2dPbmZjcEVEYktIU0tIQzQKLS0tIHQ2bm44c01YS2VQUURlRjA0Zmgx
            MXRiMnpBTE1scWdFazVDckxqSVllYlEKCgdL73mCylMIR0DCHefzNBLVl8rMYVg3
            iBQ/LgLBmWZsBPed5xVg7DmoD9i6UuoO+BL0QN9i4vZyjmHgCjwbcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-02T07:08:43Z"
    mac: ENC[AES256_GCM,data:V1GPSfMlrzy+VS74cntYHiGiMPd7KCSxoLm3bEBUbS6rsCsRYSZK3j/hri1tGAE1xB1De24FIoHHcY0WmEx/p9kpeemPJjRUBzfzyZEK0NfGKIEryZWvIexQafhJ1y7x2A6C7DaAKydHhXYGUc3tvOkYjEvadIVy7JHJEMecMvE=,iv:ZUSEtOZvUw1SsALA9oLMSWgqIpUtV20ufBaXHERxzr8=,tag:lQ3nLVQdQHu47OJNSlf58Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
