---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: oauth2-proxy
  namespace: argocd-central
  labels:
    service: "oauth2-proxy"
    owner: "team-infra-sre"
    project: "oauth2-proxy"
    organization: "infrastructure"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          # Add other clusters during migration to argocd-central
          - cluster: shared-application-2094-cluster
            env: "ppr"
            id: "2803"
            name: 2803-oauth2-proxy
  template:
    metadata:
      name: "oauth2-proxy-{{.env}}-{{.id}}"
      namespace: argocd-central
      labels:
        service: "oauth2-proxy"
        owner: "team-infra-sre"
        project: "oauth2-proxy"
        organization: "infrastructure"
        env: '{{.env}}'
    spec:
      project: oauth2-proxy
      sources:
        - chart: oauth2-proxy
          repoURL: https://oauth2-proxy.github.io/manifests
          targetRevision: 7.12.18
          helm:
            valueFiles:
              - "$values/deploy/platform-2220-cluster/applications/tools/oauth2-proxy/per-cluster-conf/{{.name}}.values.yaml"
        - repoURL: https://github.com/LedgerHQ/sre-argocd.git
          targetRevision: main
          ref: values
        - repoURL: https://github.com/LedgerHQ/sre-argocd.git
          targetRevision: main
          path: "deploy/platform-2220-cluster/applications/tools/oauth2-proxy/per-cluster-conf/2803-manifests/"
      destination:
        name: '{{.cluster}}'
        namespace: '{{.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

