---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: oauth2-proxy
  namespace: argocd-central
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: oauth2-proxy
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
