---
apiVersion: v1
kind: Namespace
metadata:
  name: backstage
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: backstage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: backstage project
  sourceRepos:
    - 'https://github.com/LedgerHQ/ledger-backstage.git'
    - 'ghcr.io'
  destinations:
    - namespace: backstage
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
