---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vault-argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Vault - Argocd project (Appset, etc.)
  sourceRepos:
    - "*"
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
