---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  labels:
    service: "argocd"
    env: "production"
spec:
  project: internal
  source:
    repoURL: https://github.com/LedgerHQ/sre-argocd.git
    targetRevision: main
    path: deploy/prd-atlas-ovh-rbx/applications
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated: {}
