apiVersion: v1
kind: Secret
metadata:
    name: argocd-helm-values
    labels:
        app.kubernetes.io/part-of: argocd
stringData:
    dex.googlegroups.clientID: ENC[AES256_GCM,data:n7ofFXRr+OFrK9m20jBT/2OAD3A+KnUYlUUyaKVbqk3vLGNhf3MW8MpDr33sEZXhySksT7+USsyogOM1xYVZWfBcDEEN1ODw,iv:1XnL/cERISnZahhtBZtLWL7skA0hrEUjx1mvQbheIoE=,tag:8ceg7gp11oeO4K3aQS1azA==,type:str]
    dex.googlegroups.clientSecret: ENC[AES256_GCM,data:55MhJT4FmK/tTzw0JySNjhrX5SwrOql862r2ImAge2N4Mns=,iv:+NUnqgk6tmVCqersMaRw9c9MFx1MDUycKLYiupfDwPY=,tag:S0jksk7GhL0iy9wp9ciBrw==,type:str]
    webhook.github.secret: ENC[AES256_GCM,data:m1k22nddge1sRQEbGBrmFxvu1nHooWH6nmPW6lxO,iv:rLcp4JgXteY6o54JgErAfcLQW9ap7xOuEq65qCkTK7c=,tag:oolIoQSp0UNx+Tvx8YkEig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1cy0dfzdgkflyekgt8pf54wemhudm3wj5gzmc2jcc2jr2nkcuggwq2defr5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZGdlLzJSYWdqSGhWeVI1
            RDc0K3hUUEltNEQwS0VybXp1K3EwZjZPYWtFCkkyMHJFYzhmTktZMGRzdThRMDMv
            TzNuUW04d3ltb2FHby9sZ1ZzR1Z5VTAKLS0tIE9iNlA3aDhlZlJ3cVdPazd1dnF6
            S1AyTGRrQzRzZWJVZEVUM3VYNFJpZG8K60k0F2wICS/Az1wpFgwOrlAb+Pem8OcU
            oi0LtVzX5vGIhcEnlsyBcbOKo59Alk8HYQsaTLjGRB4tQd0mHsfusA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-11T14:50:52Z"
    mac: ENC[AES256_GCM,data:61eob0QhtbXATdAZQq0YFODROVDmUBRqHDLqZOTX89QMxeLaObjwdenTKZ2Nzev2+cP3TlpsfebXSdobbARUU7Od8xuQicNA6ifwKHJGbXQfiW9dYwz/VJaJSvU3mHBDcAw9+Z9hGofRShMy+XwYzEoDj3Dui2FCrrITgIk4eso=,iv:6x6ReeeVO7cBYtCAKXAsvJeZnIyTG9GqJn+DIvDtLUA=,tag:JmlJegrlZkHrRJtFgK50hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
